channels:
  - conda-forge

dependencies:
  - python=3.12.3          
  - pip=23.2.1  
  - nodejs=22.11.0
  - pip:
    - robotframework==7.1.1
    - robotframework-browser==19.1

rccPostInstall:
  - rfbrowser init