# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml

channels:
  - conda-forge

dependencies:
  # packages listed here are fetched and installed from conda-forge. 
  - python>=3.12            
  - pip=23.2.1  
  - nodejs>=20
  - pip:
    # packlages listed here are fetched from pypi.org and installed using pip.
    - robotframework>=7
    - robotframework-browser==18.2.0

rccPostInstall:
  - rfbrowser init   # Initialization command for Playwright (npm)

